### PR TITLE
add correlation id between lua fields to configurator

### PR DESCRIPTION
**Pull request by offer-shmuely**
add correlation id between lua fields to configurator (messages.json), 
so we can have help string and units on the up coming color-screen lua script

### CODE REVIEW

**Comment by offer-shmuely** [comment]
this is required to achieve the following enhancements

image

**Comment by offer-shmuely** [comment]
@egonl can you take a look?

**Comment by egonl** [comment]
Looks good, but I don't think it belongs in master yet. First we have to release RF2. Until then no big changes.

**Comment by offer-shmuely** [comment]
Let me know when it will be good time...

**Comment by offer-shmuely** [comment]
this id's help getting the help comments from the configurator
without duplicate the text, without writing it again manually in one of the script files. (same text as in the configurator, if the configurator updated, the lua script can be updated automatically)

this is a sample of comments that I get using this id's

image

image

**Comment by egonl** [comment]
Manually merged in #48

**Pull request closed without merging**
